import './globals.css'
import type { Metadata } from 'next'
import { Header } from './components/header/Header'
import { Footer } from './components/footer/Footer'
import { fonts } from './fonts'

export const metadata: Metadata = {
  title: 'Foodeli - Landing Page',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="pt-br" className={`${fonts}`}>
      <body className="flex flex-col bg-background text-text items-start gap-4 p-4 sm:px-[5%]">
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  )
}
