import type { Metadata } from 'next'
import '../styles/globals.css'
import { poppins, corugette, sriracha } from './fonts'

const fonts = `${poppins.variable} ${corugette.variable} ${sriracha.variable}`

export const metadata: Metadata = {
  title: 'Foodeli - Landing Page',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="pt-br" className={fonts}>
      <head>
        <>
          {/* <script crossOrigin="anonymous" src="//unpkg.com/react-scan/dist/auto.global.js" /> */}
        </>
      </head>
      <body className={"light flex flex-col items-start gap-4 p-4 sm:px-[5%] "+ fonts}>{children}</body>
    </html>
  )
}
